<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CFG" nsURI="www.CFG.com" nsPrefix="CFG">
  <eClassifiers xsi:type="ecore:EClass" name="ControlFlowGraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" upperBound="-1"
        eType="#//Node" derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cfPrev" upperBound="-1"
        eType="#//Node" eOpposite="#//Node/cfNext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cfNext" upperBound="-1"
        eType="#//Node" containment="true" eOpposite="#//Node/cfPrev"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dfNext" upperBound="-1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BranchNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatementNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="JoinNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="SourceNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="DestinatuinNode" eSuperTypes="#//Node"/>
</ecore:EPackage>
