<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml"
    nsURI="http://uml/1.0" nsPrefix="uml">
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subvertex" upperBound="-1"
        eType="#//StateVertex" containment="true" eOpposite="#//StateVertex/subvertexOf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateVertex" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subvertexOf" lowerBound="1"
        eType="#//StateMachine" eOpposite="#//StateMachine/subvertex"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoState" eSuperTypes="#//StateVertex"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionState" eSuperTypes="#//StateVertex"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//StateVertex"/>
</ecore:EPackage>